### ISSUE TITLE
track_visit transaction rolling back and not recording in postgre/heroku

### ISSUE THREAD

**Issue by Abello966** [ankane/ahoy#153]
Hello, I've been having some problems with ahoy in my production environment (heroku with Postgre DB). In development (SQLite) it works just fine.
I've activated debugging and deactivated geocoding (fearing it was causing a timeout) and I listened to the heroku logs to get this:

2016-03-04T17:47:11.610116+00:00 app[web.1]: Started POST "/ahoy/visits" for XXX.XXX.XXX at 2016-03-04 17:47:11 +0000
2016-03-04T17:47:11.618696+00:00 app[web.1]: Processing by Ahoy::VisitsController#create as JSON
2016-03-04T17:47:11.618766+00:00 app[web.1]:   Parameters: {"visit_token"=>"790283a2-333c-404b-ab92-c795f29388bb", "visitor_token"=>"585e6357-6af6-4d29-9915-9fca4535f914", "platform"=>"Web", "landing_page"=>"https://XXXXXXX", "screen_width"=>"1366", "screen_height"=>"768", "referrer"=>"https://XXXXXXX"}
2016-03-04T17:47:11.622786+00:00 app[web.1]:   User Load (1.3ms)  SELECT  "users".\* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
2016-03-04T17:47:11.632132+00:00 app[web.1]:    (1.0ms)  BEGIN
2016-03-04T17:47:11.642307+00:00 app[web.1]:    (3.8ms)  ROLLBACK
2016-03-04T17:47:11.643443+00:00 app[web.1]: Completed 200 OK in 25ms (Views: 0.5ms | ActiveRecord: 6.1ms)

I assume the rollback means it had some kind of error during insertion, but I can't get it to show what it is. Anyone has a clue on what could it be?

**Comment by Abello966** [comment]
my config/initializers/ahoy.rb looks like this: 
`class Ahoy::Store < Ahoy::Stores::ActiveRecordStore
  Ahoy.geocode = false
  Ahoy.quiet = false
  # customize here
end
`

**Comment by Abello966** [comment]
I made some changes to include some logging in the track_visit function, and its interesting to see that it does not return. After the visit.save! line nothing else is executed

2016-03-04T18:20:31.432268+00:00 app[web.1]: initializing track_visit
2016-03-04T18:20:31.438147+00:00 app[web.1]:   User Load (3.7ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
2016-03-04T18:20:31.447009+00:00 app[web.1]: right before save
2016-03-04T18:20:31.452593+00:00 app[web.1]:    (5.3ms)  BEGIN
2016-03-04T18:20:31.458227+00:00 app[web.1]:    (1.9ms)  ROLLBACK
(there should be here "exiting track_visit", but it's not)

This means its crashing somewhere, right?

**Comment by Abello966** [comment]
visit.validate! raises no errors

**Comment by monfresh** [comment]
@Abello966 This is because the database has a unique index for the `visitor_token`. Your app is attempting to create a new visit with the same `visitor_token`, and because the DB has a uniqueness constraint, it will fail and rollback. The reason why there is no crash or other helpful message is because the code is rescuing that exception [here](https://github.com/ankane/ahoy/blob/master/lib/ahoy/stores/active_record_token_store.rb#L21) and not doing anything. @ankane I think it would be helpful to output a user-friendly message instead of doing nothing.

This was confusing to me too at first. A visit in Ahoy is a one-time event that lasts a certain amount of time. The default is 4 hours, but it can be configured. I thought that I could use `track_visit` to track page views, so I was calling `track_visit` in multiple controllers. When using the `LogStore`, this actually works great. It writes multiple lines to the log, even when the `visitor_token` hasn't changed yet (i.e the cookie hasn't expired yet). However, when using the `ActiveRecordTokenStore`, a visit is just that first entry for each cookie. 

For example, when a user first visits your site, it creates a visit. Then, if the user keep visiting other pages on your site, the user will still only have one visit. Those other pages won't be tracked, unless you use events to track the page views. Once the user is inactive for 4 hours and the `visit_token` expires, then when they come back to your site, they will have a new visit.

@ankane Is that a correct assessment?

**Comment by activestylus** [comment]
Same problem here, not sure if it's related but right after the ROLLBACK statement it always shows this error:

`FAIL-SAFE RuntimeError: can't modify frozen String`

**Comment by ankane** [comment]
Hey @activestylus, I've fixed the frozen string error in Safely. If you add Safely master to your Gemfile, you should be able to see the actual error.

```ruby
gem "safely_block", github: "ankane/master", require: false
```

**Comment by activestylus** [comment]
Thanks for the prompt reply, currently installing but a heads up that the proper Gemfile listing is:

```ruby
gem "safely_block", github: "ankane/safely", require: false
```

This correctly eliminates the runtime error, but I'm still getting rollbacks on my visits, even when I use a fresh session, clear my cache/cookies or even try it with a VPN connection:

```
SQL (0.6ms)  INSERT INTO "visits" ("visit_token", "visitor_token", "ip", "user_agent", "landing_page", "browser", "os", "device_type", "started_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING "id"  [["visit_token", "d1fc5681-3158-4ba2-b10d-39f8212f2a88"], ["visitor_token", "644b74bf-d6a3-49f1-b02f-6918edac41be"], ["ip", "12.23.4.123"], ["user_agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"], ["landing_page", "http://mysite.com/home"], ["browser", "Chrome"], ["os", "Mac OS X"], ["device_type", "Desktop"], ["started_at", 2017-02-21 10:56:42 UTC]]
   (2.0ms)  SELECT COUNT(*) FROM "users" WHERE "users"."deleted_at" IS NULL AND "users"."domain_name" = $1  [["domain_name", "mysite.com"]]
User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."deleted_at" IS NULL AND "users"."domain_name" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["domain_name", "mysite.com"], ["LIMIT", 1]]
   (0.6ms)  ROLLBACK
```

I see no other data or errors thrown - Any idea why it's not recording the visits?

**Comment by ankane** [comment]
Nice catch, updated. It's a bit late here :) My recommendation would be to fork Ahoy and add extra logging to see where the rollback happens.

**Comment by rhannequin** [comment]
Method `#track_visit` from `Ahoy::Stores::ActiveRecordTokenStore` when saving `visit` is the one rolling back for me. Exception `#<ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_visits_on_visit_token"` is thrown.

I removed `unique: true` from `add_index :visits, [:visit_token], unique: true` in `CreateVisits` migration.

The rollback stopped and the queries from `ahoy.track_visit` worked.

**Comment by rhannequin** [comment]
Ok sorry it may not be a good idea because now I have a new `Visit` object saved for each request. So maybe this rollback thing is about not duplicating `Visit` objects?

**Comment by ankane** [comment]
Going to close as I was never able to reproduce. Feel free to open a new issue with more info if someone figures out what's going on.
